config/routes.rb
# frozen_string_literal: true

Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :stores
  end
end

app/models/spree/store.rb
module Spree
  class Store < ActiveRecord::Base
    has_and_belongs_to_many :products, :join_table => 'spree_products_stores'
    has_many :taxonomies
    has_many :orders

    has_many :store_payment_methods
    has_many :payment_methods, :through => :store_payment_methods

    has_many :store_shipping_methods
    has_many :shipping_methods, :through => :store_shipping_methods

    has_and_belongs_to_many :promotion_rules, :class_name => 'Spree::Promotion::Rules::Store', :join_table => 'spree_promotion_rules_stores', :association_foreign_key => 'promotion_rule_id'

    validates_presence_of :name, :code, :domains

    before_create :ensure_default_exists_and_is_unique

    scope :default, lambda { where(:default => true) }
    scope :by_domain, lambda { |domain| where("domains like ?", "%#{domain}%") }

    has_attached_file :logo,
      :styles => { :mini => '48x48>', :small => '100x100>', :medium => '250x250>' },
      :default_style => :medium,
      :url => 'stores/:id/:style/:basename.:extension',
      :path => 'stores/:id/:style/:basename.:extension',
      :convert_options => { :all => '-strip -auto-orient' }

    def self.current(store_key = nil)
      current_store = Store.find_by(code: store_key) || Store.by_domain(store_key).first
      current_store || first_found_default
    end

    def self.first_found_default
      @cached_default ||= Store.default.first
    end

    def ensure_default_exists_and_is_unique
      if default and not Store.default.empty?
        Store.update_all(default: false)
      elsif Store.default.empty?
        self.default = true
      end
    end
  end
end

app/controllers/spree/admin/stores_controller.rb
# frozen_string_literal: true

module Spree
  module Admin
    class StoresController < Spree::Admin::ResourceController
      before_action :load_payment_methods
      before_action :load_shipping_methods

      def index
        @stores = @stores.ransack(name_or_domains_or_code_cont: params[:q]).result if params[:q]
        @stores = @stores.where(id: params[:ids].split(',')) if params[:ids]

        respond_with(@stores) do |format|
          format.html
          format.json
        end
      end

      private

      def load_payment_methods
        @payment_methods = Spree::PaymentMethod.all
      end

      def load_shipping_methods
        @shipping_methods = Spree::ShippingMethod.all
      end
    end
  end
end

app/views/admin/stores/edit.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1><%= t("editing_store") %></h1>
<%= render "shared/error_messages", :target => @store %>
<%= form_for(@store, :url => object_url, :html => { :method => :put }) do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <p class="form-buttons">
    <%= button t('update') %>
    <%= t("or") %> <%= link_to t("actions.cancel"), admin_stores_url %>
  </p>
<% end %>

app/views/admin/stores/index.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<div class='toolbar'>
  <ul class='actions'>
    <li>
      <%= button_link_to t("new_store"), new_object_url, :icon => 'add'  %>
    </li>
  </ul>
  <br class='clear' />
</div>

<h1><%= t("stores") %></h1>

<table class="index">
  <thead>
    <th><%= t("name") %></th>
    <th><%= t("code") %></th>
    <th><%= t("send_mails_as") %></th>
    <th><%= t("domains") %></th>
    <th><%= t("action") %></th>
  </thead>
  <tbody>
    <% @stores.each do |store|%>
      <tr id="<%= dom_id store %>">
        <td width="120px"><%= store.name %></td>
        <td width="80px"><%= store.code %></td>
        <td width="80px"><%= store.email %></td>
        <td width="220"><%= store.domains %></td>
        <td width="140px">
          <%= link_to_edit store %> &nbsp;
          <%= link_to_delete store %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/stores/new.html.erb
<%= render :partial => 'admin/shared/configuration_menu' %>

<h1><%= t("new_store") %></h1>
<%= render "shared/error_messages", :target => @store %>

<%= form_for(:store, :url => collection_url) do |f| %>
  <%= render :partial => "form", :locals => { :f => f } %>
  <p class="form-buttons">
    <%= button t('continue') %>
    <%= t("or") %> <%= link_to t("actions.cancel"), admin_stores_url %>
  </p>
<% end %>