config/routes.rb
# frozen_string_literal: true

Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :stores
  end
end

app/models/spree/store.rb
module Spree
  class Store < ActiveRecord::Base
    has_and_belongs_to_many :products, :join_table => 'spree_products_stores'
    has_many :taxonomies
    has_many :orders

    has_many :store_payment_methods
    has_many :payment_methods, :through => :store_payment_methods

    has_many :store_shipping_methods
    has_many :shipping_methods, :through => :store_shipping_methods

    has_and_belongs_to_many :promotion_rules, :class_name => 'Spree::Promotion::Rules::Store', :join_table => 'spree_promotion_rules_stores', :association_foreign_key => 'promotion_rule_id'

    validates_presence_of :name, :code, :domains

    before_create :ensure_default_exists_and_is_unique

    scope :default, lambda { where(:default => true) }
    scope :by_domain, lambda { |domain| where("domains like ?", "%#{domain}%") }

    has_attached_file :logo,
      :styles => { :mini => '48x48>', :small => '100x100>', :medium => '250x250>' },
      :default_style => :medium,
      :url => 'stores/:id/:style/:basename.:extension',
      :path => 'stores/:id/:style/:basename.:extension',
      :convert_options => { :all => '-strip -auto-orient' }

    def self.current(store_key = nil)
      current_store = Store.find_by(code: store_key) || Store.by_domain(store_key).first
      current_store || first_found_default
    end

    def self.first_found_default
      @cached_default ||= Store.default.first
    end

    def ensure_default_exists_and_is_unique
      if default and not Store.default.empty?
        Store.update_all(default: false)
      elsif Store.default.empty?
        self.default = true
      end
    end
  end
end

app/controllers/spree/admin/stores_controller.rb
# frozen_string_literal: true

module Spree
  module Admin
    class StoresController < Spree::Admin::ResourceController
      before_action :load_payment_methods
      before_action :load_shipping_methods

      def index
        @stores = @stores.ransack(name_or_domains_or_code_cont: params[:q]).result if params[:q]
        @stores = @stores.where(id: params[:ids].split(',')) if params[:ids]

        respond_with(@stores) do |format|
          format.html
          format.json
        end
      end

      private

      def load_payment_methods
        @payment_methods = Spree::PaymentMethod.all
      end

      def load_shipping_methods
        @shipping_methods = Spree::ShippingMethod.all
      end
    end
  end
end

app/views/spree/admin/stores/_currency_field.html.erb
<div class="four columns">
  <%= f.field_container :default_currency do %>
    <%= f.label :default_currency, Spree.t(:default_currency) %>
    <%= f.text_field :default_currency %>
  <% end %>
</div>

app/views/spree/admin/stores/_form.html.erb
<div data-hook="admin_store_form_fields">
  <div class="alpha four columns">
    <%= f.field_container :name do %>
      <%= f.label :name, I18n.t('spree.store_name') %><br />
      <%= f.text_field :name, :class => 'fullwidth' %>
      <%= error_message_on :store, :name %>
    <% end %>
  </div>

  <div class="four columns">
    <%= f.field_container :code do %>
      <%= f.label :code, I18n.t('spree.store_code') %><br />
      <%= f.text_field :code, :class => 'fullwidth' %>
      <%= error_message_on :store, :code %>
    <% end %>
  </div>

  <div class="two columns">
    <%= f.field_container :default do %>
      <%= f.label :default, I18n.t('spree.default') %>
      <ul>
        <li><%= f.radio_button :default, "true", :class => 'fullwidth' %> <%= I18n.t('spree.say_yes') %></li>
        <li><%= f.radio_button :default, "false", :class => 'fullwidth' %> <%= I18n.t('spree.say_no') %></li>
      </ul>
      <%= error_message_on :store, :default %>
    <% end %>
  </div>

  <div class="four columns">
    <%= f.field_container :mail_from_address do %>
      <%= f.label :mail_from_address, I18n.t('spree.send_mails_as') %><br />
      <%= f.text_field :mail_from_address, :class => 'fullwidth' %>
      <%= error_message_on :store, :mail_from_address %>
    <% end %>
  </div>

  <div class="four columns">
    <%= f.field_container :default_currency do %>
      <%= f.label :default_currency, I18n.t('spree.default_currency') %>
      <%= f.text_field :default_currency %>
    <% end %>
  </div>

  <div class="six columns">
    <%= f.field_container :url do %>
      <%= f.label :url, I18n.t('spree.domains') %><br />
      <%= f.text_area :url, :cols => 60, :rows => 4, :class => 'fullwidth' %>
      <%= error_message_on :store, :url %>
    <% end %>
  </div>

  <div class="eight columns">
    <%= image_tag @store.logo.url %>
    <%= f.field_container :logo do %>
      <%= f.label :logo, I18n.t('spree.logo') %><br />
      <%= f.file_field :logo %>
      <%= error_message_on :store, :logo %>
    <% end %>
  </div>

  <div class='row'>
    <div class="alpha six columns">
      <%= f.field_container :payment_methods do %>
        <%= f.label :payment_methods, I18n.t('spree.payment_methods') %><br />
        <% @payment_methods.each do |payment_method| %>
          <label class="sub">
            <%= check_box_tag 'store[payment_method_ids][]', payment_method.id, @store.payment_methods.include?(payment_method) %>
          </label> &nbsp;
          <%= payment_method.name %>
          <br>
        <% end %>
        <%= hidden_field_tag 'store[payment_method_ids][]', '' %>
      <% end %>
    </div>

    <div class="omega six columns">
      <%= f.field_container :shipping_methods do %>
        <%= f.label :shipping_methods, I18n.t('spree.shipping_methods') %><br />
        <% @shipping_methods.each do |shipping_method| %>
          <label class="sub">
            <%= check_box_tag 'store[shipping_method_ids][]', shipping_method.id, @store.shipping_methods.include?(shipping_method) %>
          </label> &nbsp;
          <%= shipping_method.name %>
          <br>
        <% end %>
        <%= hidden_field_tag 'store[shipping_method_ids][]', '' %>
      <% end %>
    </div>
  </div>
</div>

app/views/spree/admin/stores/_multi_domain_fields.html.erb
<div data-hook="admin_store_multi_domain_fields">
  <div class="two columns">
    <%= f.field_container :default do %>
      <%= f.label :default, Spree.t(:default) %>
      <ul>
        <li><%= f.radio_button :default, "true", :class => 'fullwidth' %> <%= Spree.t(:say_yes) %></li>
        <li><%= f.radio_button :default, "false", :class => 'fullwidth' %> <%= Spree.t(:say_no) %></li>
      </ul>
      <%= error_message_on :store, :default %>
    <% end %>
  </div>

  <div class="eight columns">
    <% if @store.logo.exists? %>
      <%= image_tag @store.logo %>
    <% end %>
    <%= f.field_container :logo do %>
      <%= f.label :logo, Spree.t(:logo) %><br />
      <%= f.file_field :logo %>
      <%= error_message_on :store, :logo %>
    <% end %>
  </div>

  <div class='row'>
    <div class="alpha six columns">
      <%= f.field_container :payment_methods do %>
        <%= f.label :payment_methods, Spree.t(:payment_methods) %><br />
        <% @payment_methods.each do |payment_method| %>
          <label class="sub">
            <%= check_box_tag 'store[payment_method_ids][]', payment_method.id, @store.payment_methods.include?(payment_method) %>
          </label> &nbsp;
          <%= payment_method.name %>
          <br>
        <% end %>
        <%= hidden_field_tag 'store[payment_method_ids][]', '' %>
      <% end %>
    </div>

    <div class="omega six columns">
      <%= f.field_container :shipping_methods do %>
        <%= f.label :shipping_methods, Spree.t(:shipping_methods) %><br />
        <% @shipping_methods.each do |shipping_method| %>
          <label class="sub">
            <%= check_box_tag 'store[shipping_method_ids][]', shipping_method.id, @store.shipping_methods.include?(shipping_method) %>
          </label> &nbsp;
          <%= shipping_method.name %>
          <br>
        <% end %>
        <%= hidden_field_tag 'store[shipping_method_ids][]', '' %>
      <% end %>
    </div>
  </div>
</div>

app/views/spree/admin/stores/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= I18n.t('spree.editing_store') %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= link_to I18n.t('spree.back_to_store_list'), spree.admin_stores_path, :icon => 'icon-arrow-left' %>
  </li>
<% end %>

<div data-hook="admin_store_edit_form_header">
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @store } %>
</div>

<div data-hook="admin_store_edit_form">
  <%= form_for [:admin, @store], :html => {:multipart => true} do |f| %>
    <fieldset class="no-border-top">
      <%= render :partial => 'form', :locals => { :f => f } %>

      <div class="clear"></div>

      <div data-hook="admin_store_edit_form_buttons">
        <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/spree/admin/stores/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= I18n.t('spree.stores') %>
<% end %>

<% content_for :page_actions do %>
  <% if can?(:create, Spree::Store) %>
    <li>
      <%= link_to I18n.t('spree.new_store'), new_object_url, :icon => 'icon-plus', :id => 'admin_new_store_link' %>
    </li>
  <% end %>
<% end %>

<table class="index" id='listing_stores'>
  <colgroup>
    <col style="width: 120px">
    <col style="width: 80px">
    <col style="width: 80px">
    <col style="width: 220px">
    <col style="width: 15%">
  </colgroup>
  <thead>
    <th><%= I18n.t('spree.store_name') %></th>
    <th><%= I18n.t('spree.store_code') %></th>
    <th><%= I18n.t('spree.send_mails_as') %></th>
    <th><%= I18n.t('spree.domains') %></th>
    <th data-hook="admin_stores_index_header_actions" class="actions"></th>
  </thead>
  <tbody>
    <% @stores.each do |store|%>
      <tr id="<%= spree_dom_id store %>"
          data-hook="admin_stores_index_rows" class="<%= cycle('odd', 'even') %>">
        <td><%= store.name %></td>
        <td><%= store.code %></td>
        <td><%= store.mail_from_address %></td>
        <td><%= store.url %></td>
        <td data-hook="admin_stores_index_row_actions" class="actions">
          <% if can? :update, store %>
            <%= link_to_edit store, :no_text => true %>
          <% end %>
          <% if can? :destroy, store %>
            <%= link_to_delete store, :no_text => true %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/stores/new.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= I18n.t('spree.new_store') %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= link_to I18n.t('spree.back_to_store_list'), spree.admin_stores_path, :icon => 'icon-arrow-left' %>
  </li>
<% end %>

<div data-hook="admin_store_new_form_header">
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @store } %>
</div>

<div data-hook="admin_store_new_form">
  <%= form_for [:admin, @store], :html => {:multipart => true}  do |f| %>
    <fieldset class="no-border-top">
      <%= render :partial => 'form', :locals => { :f => f } %>

      <div class="clear"></div>

      <div data-hook="admin_store_new_form_buttons">
        <%= render :partial => 'spree/admin/shared/new_resource_links' %>
      </div>
    </fieldset>
  <% end %>
</div>